# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b424f4426c58881ace87efe34a98445601fc7b46f2d78216f27cb0adacfe577e8967e068ed643d642664e9b8272aefbfca335739973507593b2634f501217e

test:
  secret_key_base: 0f6a1575b245ee7580a9e2eaae46c359600ea2ba073c432c20cee466f33188bae66fa29cf6355a6e70c1018e71970783e269f1b112dcdfa6d9ccbf91808c8ebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
